services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres.fughlfhurpnawjstlwjb:trW7nI9QJU2W0Gyq@aws-1-us-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
      DIRECT_URL: "postgresql://postgres.fughlfhurpnawjstlwjb:trW7nI9QJU2W0Gyq@aws-1-us-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      PUBLIC_VERIFY_URL: ${PUBLIC_VERIFY_URL}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      ENABLE_SWAGGER: ${ENABLE_SWAGGER:-false}
      NODE_ENV: production
    restart: unless-stopped
